config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'signup' => 'devise/registrations#new'
    get 'login' => 'devise/sessions#new'
    get 'logout' => 'devise/sessions#destroy'
  end

  root 'posts#index'

  resources :posts, only: %i[index show create update destroy] do
    get 'feed', on: :collection
  end

  resources :comments, only: %i[index create update destroy]

  resources :users, only: %i[show] do
    get 'me', on: :collection
  end

  resources :word_cloud, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  paginates_per 10
end

app/models/post.rb
# require 'natto'

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  paginates_per 10

  def self.word_cloud_of(user)
    # nm = Natto::MeCab.new
    # document = user.posts.pluck(:body).join(' ')
    words = []

    # nm.parse(document) do |n|
    #   words << n.surface unless n.feature =~ /助詞|\?/
    # end

    words.group_by(&:itself).map do |key, value|
      {word: key, count: value.size}
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update destroy]

  def index
    @comments = Comment.includes(:user).where(post_id: params[:post_id]).order(created_at: :desc).page(params[:page])
    render json: @comments, each_serializer: CommentSerializer
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    render json: @comment, serializer: CommentSerializer
  rescue => e
    handle_error(e)
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update!(comment_params)
    render json: @comment, serializer: CommentSerializer
  rescue => e
    handle_error(e)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    comment_id = @comment.id
    @comment.destroy!
    render json: comment_id
  rescue => e
    handle_error(e)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def handle_error(e)
    logger.error(e.message)
    render json: {status: :error, message: e.message}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update destroy]

  def index
  end

  def feed
    @posts = Post.includes(:user).order(created_at: :desc).page(params[:page])
    render json: @posts, each_serializer: PostSerializer
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create!(post_params)
    render json: @post, serializer: PostSerializer
  rescue => e
    handle_error(e)
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update!(post_params)
    render json: @post, serializer: PostSerializer
  rescue => e
    handle_error(e)
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    post_id = @post.id
    @post.destroy!
    render json: post_id
  rescue => e
    handle_error(e)
  end

  private
  def post_params
    params.require(:post).permit(:body)
  end

  def handle_error(e)
    logger.error(e.message)
    render json: {status: :error}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def me
    render json: current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/word_cloud_controller.rb
class WordCloudController < ApplicationController
  def index
    words = Post.word_cloud_of(User.find(params[:user_id]))
    render json: words
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.header
  ul
    li
      = link_to root_path do
        .header__logo
          |YumeLog
    - if user_signed_in?
      li
        = link_to 'Mypage', user_path(current_user.id)
      li 
        = link_to 'Logout', logout_path
    - else
      li
        = link_to 'Login', login_path
      li
        = link_to 'SignUp', signup_path

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title
      |Yumelog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'

  body
    = render 'layouts/header'
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/posts/index.html.slim
#timeline
= javascript_include_tag 'webpack/timeline.bundle'

app/views/posts/show.html.slim
.postDetail
  .postDetail__header
    .postDetail__header__username
      | 投稿者：
      = link_to @post.user.name, user_path(@post.user_id)
    = @post.created_at.strftime('%Y年%m月%d日 %H:%M')
    
  .postDetail__content
    = @post.body

#comment
= javascript_include_tag 'webpack/comment.bundle'

app/views/users/show.html.slim
/= javascript_include_tag 'http://d3js.org/d3.v3.min.js'
/= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/d3-cloud/1.2.4/d3.layout.cloud.js'

.wordCloud
  .wordCloud__title
    = @user.name
    |さんの夢によく出る言葉

  #word_cloud
  /= javascript_include_tag 'webpack/word_cloud.bundle.js'